### ISSUE TITLE
5.36 fails tests | op.sort

### ISSUE THREAD

**Issue by shawnlaffan** [StrawberryPerl/Perl-Dist-Strawberry#85]
I think I looked into this before and from memory it is UTF related, so might be related to #60 

Will look into it later unless someone beats me to it.  

```
op/sort.t ............................................................
Dubious, test returned 40 (wstat 10240, 0x2800)
Failed 49/203 subtests
```

**Comment by xenu** [comment]
```
ok 154 - sort sub refcnt
gdb: unknown target exception 0xc0000028 at 0x7ffa1a0d2856

Thread 1 received signal ?, Unknown signal.
0x00007ffa1a0d2856 in ntdll!RtlRaiseStatus () from C:\Windows\SYSTEM32\ntdll.dll
(gdb) bt
#0  0x00007ffa1a0d2856 in ntdll!RtlRaiseStatus () from C:\Windows\SYSTEM32\ntdll.dll
#1  0x00007ffa1a000bb3 in ntdll!RtlUnwindEx () from C:\Windows\SYSTEM32\ntdll.dll
#2  0x00007ffa18f92eed in msvcrt!_setjmpex () from C:\Windows\System32\msvcrt.dll
#3  0x00007ff9a02e154f in perl536!Perl_qerror ()
   from C:\Users\xenu\Downloads\sp536_20230316\strawberry\perl\bin\perl536.dll
#4  0x00007ff9a038094c in perl536!Perl_vcroak ()
   from C:\Users\xenu\Downloads\sp536_20230316\strawberry\perl\bin\perl536.dll
#5  0x00007ff9a0380a27 in perl536!Perl_croak_nocontext ()
   from C:\Users\xenu\Downloads\sp536_20230316\strawberry\perl\bin\perl536.dll
#6  0x00007ff9a03810f7 in perl536!Perl_croak_no_modify ()
   from C:\Users\xenu\Downloads\sp536_20230316\strawberry\perl\bin\perl536.dll
#7  0x00007ff9a0374ea5 in perl536!Perl_sortsv ()
   from C:\Users\xenu\Downloads\sp536_20230316\strawberry\perl\bin\perl536.dll
#8  0x0000000000000001 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by shawnlaffan** [comment]
That looks to do the trick.  ```op/sort.t``` passes with those settings.
